#!/bin/zsh

# XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}

# Fixing Paths
export GEM_PATH="$XDG_DATA_HOME/ruby/gems"
export GEM_SPEC_CACHE="$XDG_DATA_HOME/ruby/specs"
export GEM_HOME="$XDG_DATA_HOME/ruby/gems"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GOPATH="$XDG_DATA_HOME"/go
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"

# Default Apps
export EDITOR="lvim"
export TERMINAL="kitty"
export BROWSER="chrome"
export VIDEO="mpv"

# Doom Emacs
export PATH="$HOME/.emacs.d/bin:$PATH"

# Ranger 
export RANGER_LOAD_DEFAULT_RC=FALSE
. "/home/mushi/.local/share/cargo/env"
