#!/bin/zsh
case "$(uname -s)" in
    Darwin)
        eval "$(/opt/homebrew/bin/brew shellenv)"
        export PATH="/opt/homebrew/bin:$PATH"
        export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"
        # eval "$(/usr/libexec/path_helper)"
        ;;
    Linux)
        ;;
    CYGWIN* | MINGW32* | MSYS* | MINGW*)
        ;;
    *)
        ;;
esac

# Doom emacs
export PATH="$HOME/.emacs.d/bin:$PATH"
