#!/bin/zsh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enable colors and change prompt:
autoload -U colors && colors

# History in cache directory:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.cache/zsh/history

autoload -U compinit && compinit -u
zstyle ':completion:*' menu select
# Auto complete with case insenstivity
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# Control bindings for programs
bindkey -s "^g" "lc\n"
bindkey -s "^h" "history 1\n"
bindkey -s "^l" "clear\n"
bindkey -s "^d" "dlfile\n"

# Source configs
# for f in ~/.config/shellconfig/*; do source "$f"; done
#source /home/brodie/.config/broot/launcher/bash/br

# Load zsh-syntax-highlighting
source ~/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
# Suggest aliases for commands
# source ~/.local/share/zsh/plugins/zsh-you-shoud-use/you-should-use.plugin.zsh 2>/dev/null
# Auto suggestions
source ~/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
bindkey ',' autosuggest-accept
# Search repos for programs that can't be found
# source /usr/share/doc/pkgfile/command-not-found.zsh 2>/dev/null

# Starship Prompt
eval "$(starship init zsh)"

# For Emacs Vterm's shell-side configuration
vterm_printf(){
    if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ); then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

# Alias
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias ls='exa'
alias e='emacsclient -a "" -c -n "$@"'

# Created by `pipx` on 2022-09-02 06:31:35
export PATH="$PATH:/Users/mushi007/.local/bin"
