#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# PATH with doom emacs
export PATH="$HOME/.emacs.d/bin":$PATH

# PATH with .cargo
export PATH="$HOME/.cargo/bin":$PATH

# PATH with .local
export PATH="$HOME/.local/bin":$PATH

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

